# Generated by Django 5.2.8 on 2025-11-11 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_empresa_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificacaoPCD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enquadravel", "✅ Enquadrável"),
                            ("sugestivo", "⚠️ Sugestivo"),
                            ("nao_enquadravel", "🚫 Não enquadrável"),
                            ("avaliacao_adicional", "🩺 Avaliação adicional"),
                            ("exame_necessario", "📄 Exame ou laudo necessário"),
                        ],
                        max_length=30,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "documentos_analisados",
                    models.TextField(
                        blank=True, help_text="Lista de documentos que foram analisados"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classificacoes",
                        to="core.pcdprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação PCD",
                "verbose_name_plural": "Classificações PCD",
                "ordering": ["-criado_em"],
            },
        ),
    ]
