# Generated by Django 5.2.8 on 2025-11-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_carga_categorias_deficiencia"),
        ("userpcd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "candidatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversas",
                        to="userpcd.candidatura",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_empresa",
                        to="core.empresa",
                    ),
                ),
                (
                    "pcd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_pcd",
                        to="core.pcdprofile",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversas",
                        to="userpcd.vaga",
                    ),
                ),
            ],
            options={
                "ordering": ["-atualizada_em"],
                "unique_together": {("pcd", "empresa", "vaga")},
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remetente_empresa",
                    models.BooleanField(
                        default=False,
                        help_text="True se remetente é empresa, False se é PCD",
                    ),
                ),
                ("conteudo", models.TextField()),
                ("lida", models.BooleanField(default=False)),
                ("enviada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="userpcd.conversa",
                    ),
                ),
            ],
            options={
                "ordering": ["enviada_em"],
            },
        ),
    ]
