# Generated by Django 5.2.8 on 2025-11-10 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userpcd", "0002_conversa_mensagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilpcdextendido",
            name="data_avaliacao_medica",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perfilpcdextendido",
            name="medico_avaliador",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "medico"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="perfilpcdextendido",
            name="observacoes_medicas",
            field=models.TextField(
                blank=True, help_text="Observações do médico avaliador"
            ),
        ),
        migrations.AlterField(
            model_name="perfilpcdextendido",
            name="status_medico",
            field=models.CharField(
                choices=[
                    ("pendente", "⏳ Pendente de Avaliação"),
                    ("enquadravel", "✅ Enquadrável"),
                    ("sugestivo", "⚠️ Sugestivo de Enquadrável"),
                    ("nao_enquadravel", "🚫 Não Enquadrável"),
                    (
                        "avaliacao_adicional",
                        "🩺 Necessidade de Avaliação Médica Adicional",
                    ),
                    (
                        "necessita_laudo",
                        "📄 Necessidade de Laudo Detalhado ou Exame Atualizado",
                    ),
                ],
                default="pendente",
                max_length=30,
            ),
        ),
    ]
