# Generated by Django 5.2.1 on 2025-05-28 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_carga_categorias_deficiencia'),
        ('userpcd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaExtendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_completude', models.IntegerField(default=60)),
                ('total_vagas_ativas', models.IntegerField(default=0)),
                ('total_candidatos_recebidos', models.IntegerField(default=0)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_extendida', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('novo_candidato', 'Novo Candidato'), ('status_vaga', 'Status da Vaga'), ('avaliacao_medica', 'Avaliação Médica'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('candidatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userpcd.candidatura')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_empresa', to='core.empresa')),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userpcd.vaga')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('novo', 'Novo Candidato'), ('visualizado', 'Currículo Visualizado'), ('contato_iniciado', 'Contato Iniciado'), ('entrevista_marcada', 'Entrevista Marcada'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='novo', max_length=20)),
                ('data_visualizacao_cv', models.DateTimeField(blank=True, null=True)),
                ('data_contato', models.DateTimeField(blank=True, null=True)),
                ('data_entrevista', models.DateTimeField(blank=True, null=True)),
                ('observacoes_empresa', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo_seletivo', to='userpcd.candidatura')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='VagaExtendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('emprego', 'Emprego'), ('capacitacao', 'Capacitação')], default='emprego', max_length=20)),
                ('numero_vagas', models.IntegerField(default=1, help_text='Número de vagas disponíveis')),
                ('duracao_capacitacao', models.CharField(blank=True, help_text='Para capacitações', max_length=100)),
                ('acesso_transporte_publico', models.BooleanField(default=False)),
                ('status_medico', models.CharField(choices=[('pendente', 'Aguardando Avaliação'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('observacoes_medicas', models.TextField(blank=True)),
                ('total_candidatos', models.IntegerField(default=0)),
                ('candidatos_compativel', models.IntegerField(default=0)),
                ('deficiencias_elegiveis', models.ManyToManyField(blank=True, to='core.categoriadeficiencia')),
                ('vaga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaga_extendida', to='userpcd.vaga')),
            ],
        ),
    ]
