# Generated by Django 5.2.8 on 2025-11-10 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usercompany", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vagaextendida",
            name="data_avaliacao_medica",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vagaextendida",
            name="medico_avaliador",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "medico"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vagas_avaliadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
