"""
Django settings for pcd project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(gvi*g4oq5gqlg0bh7@_m-dvyu#n^0)rw!71zfvs#z9-4pzp%y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'daphne',  # Deve estar antes de django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'core',
    'userpcd',
    'usercompany',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pcd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pcd.wsgi.application'
ASGI_APPLICATION = 'pcd.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'core.User'


from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.SUCCESS: 'bg-green-50 text-green-700',
    message_constants.ERROR: 'bg-red-50 text-red-700',
}

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Portal PCD Admin",
    "SITE_HEADER": "Sistema de Enquadramento PCD",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("icon.png"),
        "dark": lambda request: static("icon.png"),
    },
    "COLORS": {
        "primary": {
            "50": "134 239 172",
            "100": "74 222 128",
            "200": "34 197 94",
            "300": "22 163 74",
            "400": "21 128 61",
            "500": "22 101 52",
            "600": "20 83 45",
            "700": "22 70 42",
            "800": "20 55 36",
            "900": "20 48 34",
            "950": "5 20 15",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Dashboard",
                "icon": "dashboard",
                "link": lambda request: "/admin/",
                "items": [],
            },
            {
                "title": "Usuários",
                "icon": "people",
                "items": [
                    {
                        "title": "Usuários",
                        "link": lambda request: "/admin/core/user/",
                    },
                    {
                        "title": "Empresas",
                        "link": lambda request: "/admin/core/empresa/",
                    },
                    {
                        "title": "PCDs",
                        "link": lambda request: "/admin/core/pcdprofile/",
                    },
                    {
                        "title": "Médicos",
                        "link": lambda request: "/admin/core/medicoprofile/",
                    },
                ],
            },
            {
                "title": "Vagas & Candidaturas",
                "icon": "work",
                "items": [
                    {
                        "title": "Vagas",
                        "link": lambda request: "/admin/userpcd/vaga/",
                    },
                    {
                        "title": "Candidaturas",
                        "link": lambda request: "/admin/userpcd/candidatura/",
                    },
                ],
            },
            {
                "title": "Documentos",
                "icon": "description",
                "link": lambda request: "/admin/userpcd/documento/",
                "items": [],
            },
            {
                "title": "Notificações",
                "icon": "notifications",
                "items": [
                    {
                        "title": "Notificações PCD",
                        "link": lambda request: "/admin/userpcd/notificacao/",
                    },
                    {
                        "title": "Notificações Empresa",
                        "link": lambda request: "/admin/usercompany/notificacaoempresa/",
                    },
                ],
            },
            {
                "title": "Deficiências",
                "icon": "accessible",
                "link": lambda request: "/admin/core/categoriadeficiencia/",
                "items": [],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "core.user",
                "core.empresa",
                "core.pcdprofile",
            ],
            "items": [
                {
                    "title": "Usuários",
                    "link": lambda request: "/admin/core/user/",
                },
                {
                    "title": "Empresas",
                    "link": lambda request: "/admin/core/empresa/",
                },
                {
                    "title": "PCDs",
                    "link": lambda request: "/admin/core/pcdprofile/",
                },
            ],
        },
    ],
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Cache Configuration with Redis
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'db': 1,
        }
    }
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Celery Configuration (for async tasks)
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'